# Generated by Django 5.2.16 on 2026-07-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='🔧', max_length=8, verbose_name='İkon (emoji)'),
        ),
    ]
