# Generated by Django 5.2.16 on 2026-08-24 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0002_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=100, verbose_name='Lot / Seri Numarası')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Bu Partiden Kalan Miktar')),
                ('received_date', models.DateField(verbose_name='Geliş Tarihi')),
                ('expiry_date', models.DateField(blank=True, help_text='Yoksa boş bırak (çoğu elektronik komponentte olmaz).', null=True, verbose_name='Son Kullanma Tarihi')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='envanter.product', verbose_name='Ürün')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envanter.supplier', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Lot / Seri',
                'verbose_name_plural': 'Lotlar / Seriler',
                'ordering': ['-received_date'],
                'unique_together': {('product', 'lot_number')},
            },
        ),
    ]
